# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-04-12 06:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsplugin_filer_image', '0009_auto_20160713_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='filerimage',
            name='caption_alignment',
            field=models.CharField(blank=True, choices=[('left', 'left'), ('right', 'right'), ('center', 'center')], max_length=10, null=True, verbose_name='caption alignment'),
        ),
    ]
